#!/usr/bin/env bash
# Extract InnerTube cookie + bearer from a YouTube HAR capture and write to .env
# Usage: ./scripts/extract-innertube-creds.sh ~/Downloads/yt-subs.har
set -euo pipefail

HAR_FILE="${1:-$HOME/Downloads/yt-subs.har}"
ENV_FILE="$(dirname "$0")/../.env"

if [ ! -f "$HAR_FILE" ]; then
	echo "❌ HAR file not found: $HAR_FILE"
	echo "   Usage: $0 <path-to-har>"
	exit 1
fi

# Extract using node (handles JSON safely)
eval "$(node -e "
const fs = require('fs');
const har = JSON.parse(fs.readFileSync('$HAR_FILE', 'utf-8'));
const entries = har.log.entries;
const innertube = entries.filter(e => e.request.url.includes('youtubei/v1/'));

let cookie = null, auth = null;
for (const e of innertube) {
  for (const h of e.request.headers) {
    if (h.name.toLowerCase() === 'cookie' && h.value.length > 100) cookie = h.value;
    if (h.name.toLowerCase() === 'authorization' && h.value.length > 50) auth = h.value;
  }
  if (cookie && auth) break;
}

if (!cookie || !auth) { console.error('❌ No InnerTube auth found in HAR'); process.exit(1); }
// Base64 to avoid shell escaping issues
console.log('COOKIE_B64=' + Buffer.from(cookie).toString('base64'));
console.log('BEARER_B64=' + Buffer.from(auth).toString('base64'));
")"

# Decode and write to .env
COOKIE=$(echo "$COOKIE_B64" | base64 -d)
BEARER=$(echo "$BEARER_B64" | base64 -d)

# Remove old values
if [ -f "$ENV_FILE" ]; then
	sed -i '' '/^# InnerTube/d; /^YOUTUBE_INNERTUBE_/d' "$ENV_FILE"
fi

# Append new values
{
	echo ""
	echo "# InnerTube API — subscription feed acceleration"
	echo "# Generated by scripts/extract-innertube-creds.sh"
	echo "# Cookie expires in ~2-4 weeks. Re-run this script with a fresh HAR to refresh."
	echo "YOUTUBE_INNERTUBE_COOKIE=$COOKIE"
	echo "YOUTUBE_INNERTUBE_BEARER=$BEARER"
} >>"$ENV_FILE"

echo "✅ InnerTube credentials written to .env"
echo "   Cookie: ${#COOKIE} chars"
echo "   Bearer: ${#BEARER} chars"
